export const route = {
  // Story workspace
  home: '/',
  submission: '/submission',
  session: '/session',
  evolve: '/evolve',
  characters: '/characters',
  world: '/world',
  events: '/events',
  manuscript: '/manuscript',
  appLogs: '/logs',
  project: '/project',
  projectDetail: '/project/$projectId',
  settings: {
    index: '/settings',
    model_providers: '/settings/providers',
    story_models: '/settings/story-models',
    providers: '/settings/providers/$providerName',
    general: '/settings/general',
    interface: '/settings/interface',
    privacy: '/settings/privacy',
    shortcuts: '/settings/shortcuts',
    extensions: '/settings/extensions',
    mcp_servers: '/settings/mcp-servers',
    https_proxy: '/settings/https-proxy',
    web_search: '/settings/web-search',
    assistant: '/settings/assistant',
  },
  threadsDetail: '/threads/$threadId',
} as const
