export const route = {
  // Story workspace
  home: '/',
  submission: '/submission',
  evolve: '/evolve',
  characters: '/characters',
  world: '/world',
  events: '/events',
  manuscript: '/manuscript',
  appLogs: '/logs',
  project: '/project',
  projectDetail: '/project/$projectId',
  settings: {
    index: '/settings',
    model_providers: '/settings/providers',
    providers: '/settings/providers/$providerName',
    general: '/settings/general',
    attachments: '/settings/attachments',
    interface: '/settings/interface',
    privacy: '/settings/privacy',
    shortcuts: '/settings/shortcuts',
    extensions: '/settings/extensions',
    local_api_server: '/settings/local-api-server',
    mcp_servers: '/settings/mcp-servers',
    https_proxy: '/settings/https-proxy',
    web_search: '/settings/web-search',
    hardware: '/settings/hardware',
    assistant: '/settings/assistant',
    claude_code: '/settings/claude-code',
  },
  hub: {
    index: '/hub/',
    model: '/hub/$modelId',
  },
  localApiServerlogs: '/local-api-server/logs',
  systemMonitor: '/system-monitor',
  threadsDetail: '/threads/$threadId',
} as const
