/* eslint-disable */
// Generated by pnpm contracts:generate. Do not edit manually.
export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Engine Status */
        get: operations["engine_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_projects__project_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Turn */
        post: operations["create_turn_projects__project_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/turns/{turn_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Turn */
        get: operations["get_turn_projects__project_id__turns__turn_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/turns/{turn_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Turn */
        post: operations["approve_turn_projects__project_id__turns__turn_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/turns/{turn_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard Turn */
        post: operations["discard_turn_projects__project_id__turns__turn_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/turns/{turn_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Turn */
        post: operations["review_turn_projects__project_id__turns__turn_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Character */
        Character: {
            /** Core Desire */
            core_desire: string;
            /** Current Goal */
            current_goal?: string | null;
            /** Emotional State */
            emotional_state?: string | null;
            /** Id */
            id: string;
            /** Identity */
            identity: string;
            /**
             * Known Fact Ids
             * @default []
             */
            known_fact_ids: string[];
            /** Last Event Id */
            last_event_id?: string | null;
            /** Location */
            location?: string | null;
            /**
             * Relationships
             * @default []
             */
            relationships: components["schemas"]["Relationship"][];
            /**
             * Resources
             * @default []
             */
            resources: string[];
            /**
             * Type
             * @enum {string}
             */
            type: "active" | "npc" | "retired";
            /**
             * Version
             * @default 0
             */
            version: number;
        };
        /** CharacterIntent */
        CharacterIntent: {
            /** Action */
            action: string;
            /** Character Id */
            character_id: string;
            /** Goal */
            goal: string;
            /** Knowledge Basis */
            knowledge_basis: string[];
            /** Recognized Risk */
            recognized_risk?: string | null;
            /** Target */
            target?: string | null;
        };
        /** CommitResult */
        CommitResult: {
            candidate: components["schemas"]["TurnCandidate"];
            event: components["schemas"]["StoryEvent"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        JsonValue: unknown;
        /** NpcCandidate */
        NpcCandidate: {
            /** Current Goal */
            current_goal?: string | null;
            /** Id */
            id: string;
            /** Identity */
            identity: string;
            /** Purpose */
            purpose: string;
        };
        /** ProjectDocument */
        ProjectDocument: {
            /** Genre */
            genre: string;
            /** Id */
            id: string;
            /**
             * Schema
             * @default project/v1
             * @constant
             */
            schema: "project/v1";
            /** Theme */
            theme: string;
            /** Title */
            title: string;
            /** Tone */
            tone: string;
            /**
             * Version
             * @default 0
             */
            version: number;
        };
        /** ProjectSeed */
        ProjectSeed: {
            /** Characters */
            characters: components["schemas"]["Character"][];
            /** Genre */
            genre: string;
            /** Id */
            id: string;
            /** Theme */
            theme: string;
            /** Title */
            title: string;
            /** Tone */
            tone: string;
            world: components["schemas"]["WorldState"];
        };
        /** ProjectSnapshot */
        ProjectSnapshot: {
            /** Characters */
            characters: components["schemas"]["Character"][];
            project: components["schemas"]["ProjectDocument"];
            world: components["schemas"]["WorldState"];
        };
        /** Relationship */
        Relationship: {
            /** Character Id */
            character_id: string;
            /** Description */
            description: string;
        };
        /** ReviewIssue */
        ReviewIssue: {
            /** Code */
            code: string;
            /**
             * Evidence Ids
             * @default []
             */
            evidence_ids: string[];
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "blocking";
        };
        /** ReviewResult */
        ReviewResult: {
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["ReviewIssue"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "submission_review" | "character_review" | "world_review" | "turn_review" | "promotion_review" | "manuscript_review";
            /** Passed */
            passed: boolean;
            /** Summary */
            summary: string;
        };
        /** StateChange */
        StateChange: {
            /** Field */
            field: string;
            new_value: components["schemas"]["JsonValue"];
            old_value?: components["schemas"]["JsonValue"];
            /** Reason */
            reason: string;
            /** Target Id */
            target_id: string;
            /**
             * Target Type
             * @enum {string}
             */
            target_type: "character" | "world";
        };
        /** StatusResponse */
        StatusResponse: {
            /** Status */
            status: string;
        };
        /** StoryEvent */
        StoryEvent: {
            /** Approved By User */
            approved_by_user: boolean;
            /**
             * Character Changes
             * @default []
             */
            character_changes: components["schemas"]["StateChange"][];
            /**
             * Hidden Results
             * @default []
             */
            hidden_results: string[];
            /** Id */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Participants */
            participants: string[];
            /**
             * Public Results
             * @default []
             */
            public_results: string[];
            /** Sequence */
            sequence: number;
            /** Source Turn Id */
            source_turn_id: string;
            /** Summary */
            summary: string;
            /**
             * World Changes
             * @default []
             */
            world_changes: components["schemas"]["StateChange"][];
        };
        /** TurnCandidate */
        TurnCandidate: {
            /** Base Character Versions */
            base_character_versions: {
                [key: string]: number;
            };
            /** Base World Version */
            base_world_version: number;
            /** Id */
            id: string;
            /** Intents */
            intents: components["schemas"]["CharacterIntent"][];
            outcome: components["schemas"]["WorldOutcome"];
            /** Project Id */
            project_id: string;
            review?: components["schemas"]["ReviewResult"] | null;
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "draft" | "reviewed" | "needs_revision" | "approved" | "discarded" | "committed";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorldOutcome */
        WorldOutcome: {
            /**
             * Character Changes
             * @default []
             */
            character_changes: components["schemas"]["StateChange"][];
            /**
             * Hidden Results
             * @default []
             */
            hidden_results: string[];
            /**
             * New Npcs
             * @default []
             */
            new_npcs: components["schemas"]["NpcCandidate"][];
            /**
             * Public Results
             * @default []
             */
            public_results: string[];
            /** Summary */
            summary: string;
            /**
             * Unresolved Consequences
             * @default []
             */
            unresolved_consequences: string[];
            /**
             * World Changes
             * @default []
             */
            world_changes: components["schemas"]["StateChange"][];
        };
        /** WorldState */
        WorldState: {
            /**
             * Active Pressures
             * @default []
             */
            active_pressures: string[];
            /** Current Location */
            current_location?: string | null;
            /** Current Time */
            current_time: string;
            /**
             * Public Fact Ids
             * @default []
             */
            public_fact_ids: string[];
            /**
             * Version
             * @default 0
             */
            version: number;
            /** World Variables */
            world_variables?: {
                [key: string]: string | number | boolean | null;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    engine_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectSeed"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_projects__project_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_turn_projects__project_id__turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnCandidate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_turn_projects__project_id__turns__turn_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_turn_projects__project_id__turns__turn_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_turn_projects__project_id__turns__turn_id__discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_turn_projects__project_id__turns__turn_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewResult"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
