/* eslint-disable */
// Generated by pnpm contracts:generate. Do not edit manually.
export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Engine Status */
        get: operations["engine_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Catalog */
        get: operations["get_model_catalog_models_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Model */
        post: operations["complete_model_models_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Profiles */
        get: operations["get_model_profiles_models_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Model Profile */
        put: operations["put_model_profile_models_profiles__profile_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Model */
        post: operations["stream_model_models_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Usage */
        get: operations["model_usage_models_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Characters */
        get: operations["list_characters_projects__project_id__characters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Character */
        get: operations["get_character_projects__project_id__characters__character_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/characters/{character_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Promotion */
        post: operations["confirm_promotion_projects__project_id__characters__character_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/characters/{character_id}/promotion-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Promotion */
        post: operations["review_promotion_projects__project_id__characters__character_id__promotion_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Project */
        post: operations["close_project_projects__project_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_projects__project_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/manuscript/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Manuscript */
        get: operations["export_manuscript_projects__project_id__manuscript_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Project */
        post: operations["open_project_projects__project_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/rag/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild Index */
        post: operations["rebuild_index_projects__project_id__rag_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/rag/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_projects__project_id__rag_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenes */
        get: operations["list_scenes_projects__project_id__scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/scenes/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Scene */
        post: operations["generate_scene_projects__project_id__scenes_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/scenes/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scene */
        get: operations["get_scene_projects__project_id__scenes__scene_id__get"];
        /** Update Scene */
        put: operations["update_scene_projects__project_id__scenes__scene_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/scenes/{scene_id}/amendments/{amendment_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Amendment */
        post: operations["confirm_amendment_projects__project_id__scenes__scene_id__amendments__amendment_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/submission/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discuss Submission */
        post: operations["discuss_submission_projects__project_id__submission_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/turns/active/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Active Turn */
        post: operations["cancel_active_turn_projects__project_id__turns_active_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/turns/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Turn */
        post: operations["generate_turn_projects__project_id__turns_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/turns/{turn_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Turn */
        get: operations["get_turn_projects__project_id__turns__turn_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/turns/{turn_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Turn */
        post: operations["confirm_turn_projects__project_id__turns__turn_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/turns/{turn_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard Turn */
        post: operations["discard_turn_projects__project_id__turns__turn_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/turns/{turn_id}/request-revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Turn Revision */
        post: operations["request_turn_revision_projects__project_id__turns__turn_id__request_revision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_projects__project_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Submission */
        post: operations["finalize_submission_submissions_finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AmendmentCommitResult */
        AmendmentCommitResult: {
            amendment: components["schemas"]["EventAmendmentCandidate"];
            event: components["schemas"]["StoryEvent"];
            scene: components["schemas"]["Scene"];
        };
        /** Character */
        Character: {
            /** Core Desire */
            core_desire: string;
            /** Current Goal */
            current_goal?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Emotional State */
            emotional_state?: string | null;
            /** Id */
            id: string;
            /** Identity */
            identity: string;
            /**
             * Known Fact Ids
             * @default []
             */
            known_fact_ids: string[];
            /** Last Event Id */
            last_event_id?: string | null;
            /** Location */
            location?: string | null;
            /**
             * Relationships
             * @default []
             */
            relationships: components["schemas"]["Relationship"][];
            /**
             * Resources
             * @default []
             */
            resources: string[];
            /**
             * Type
             * @enum {string}
             */
            type: "active" | "npc" | "retired";
            /**
             * Version
             * @default 0
             */
            version: number;
        };
        /** CharacterIntent */
        CharacterIntent: {
            /** Action */
            action: string;
            /** Character Id */
            character_id: string;
            /** Goal */
            goal: string;
            /** Knowledge Basis */
            knowledge_basis: string[];
            /** Recognized Risk */
            recognized_risk?: string | null;
            /** Target */
            target?: string | null;
        };
        /** CommitResult */
        CommitResult: {
            candidate: components["schemas"]["TurnCandidate"];
            event: components["schemas"]["StoryEvent"];
        };
        /** EventAmendmentCandidate */
        EventAmendmentCandidate: {
            /** Base Workspace Revision */
            base_workspace_revision?: string | null;
            /** Base World Version */
            base_world_version: number;
            /** Draft Revision */
            draft_revision: number;
            /** Fact Ids */
            fact_ids: string[];
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Proposed Facts */
            proposed_facts: string[];
            /** Scene Id */
            scene_id: string;
            /** Source Event Ids */
            source_event_ids: string[];
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "committed";
        };
        /** Fact */
        Fact: {
            /** Id */
            id: string;
            /**
             * Introduced At
             * Format: date-time
             */
            introduced_at: string;
            /**
             * Known By
             * @default []
             */
            known_by: string[];
            /** Source Event Id */
            source_event_id: string;
            /** Statement */
            statement: string;
            /** Supersedes Fact Id */
            supersedes_fact_id?: string | null;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "public" | "private" | "secret";
        };
        /** FactCandidate */
        FactCandidate: {
            /** Id */
            id: string;
            /**
             * Known By
             * @description Must be empty when visibility is public. For private or secret facts, list every knowing character id exactly once.
             * @default []
             */
            known_by: string[];
            /** Statement */
            statement: string;
            /** Supersedes Fact Id */
            supersedes_fact_id?: string | null;
            /**
             * Visibility
             * @description Use public for facts known to everyone. Use private or secret only when knowledge is restricted to specific characters.
             * @enum {string}
             */
            visibility: "public" | "private" | "secret";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        JsonValue: unknown;
        /** KnowledgeChange */
        KnowledgeChange: {
            /**
             * Action
             * @enum {string}
             */
            action: "learn" | "forget";
            /** Character Id */
            character_id: string;
            /** Fact Id */
            fact_id: string;
            /** Reason */
            reason: string;
        };
        /** ManuscriptExport */
        ManuscriptExport: {
            /** Filename */
            filename: string;
            /** Markdown */
            markdown: string;
        };
        /** ManuscriptReviewOutput */
        ManuscriptReviewOutput: {
            /**
             * New Facts
             * @default []
             */
            new_facts: string[];
            review: components["schemas"]["ReviewResult"];
        };
        /** Message */
        Message: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant";
        };
        /** ModelCatalog */
        ModelCatalog: {
            /** Profiles */
            profiles: components["schemas"]["ModelProfile"][];
        };
        /** ModelProfile */
        ModelProfile: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Id */
            id: string;
            /**
             * Max Output Tokens
             * @default 2048
             */
            max_output_tokens: number;
            /** Model */
            model: string;
            /** Name */
            name: string;
            /** Provider Id */
            provider_id: string;
            /**
             * Reasoning Effort
             * @default disabled
             * @enum {string}
             */
            reasoning_effort: "disabled" | "low" | "high" | "max";
            /**
             * Task Type
             * @enum {string}
             */
            task_type: "character" | "resolver" | "editor" | "writer" | "embedding";
            /** Temperature */
            temperature?: number | null;
            /**
             * Timeout Seconds
             * @default 60
             */
            timeout_seconds: number;
        };
        /** ModelRequest */
        ModelRequest: {
            /** Max Output Tokens */
            max_output_tokens: number;
            /** Messages */
            messages: components["schemas"]["Message"][];
            /** Output Schema */
            output_schema?: string | null;
            /** Profile Id */
            profile_id: string;
            /**
             * Task Type
             * @enum {string}
             */
            task_type: "character" | "resolver" | "editor" | "writer" | "embedding";
            /** Temperature */
            temperature?: number | null;
            /** Timeout Seconds */
            timeout_seconds: number;
        };
        /** ModelResponse */
        ModelResponse: {
            /** Content */
            content: string;
            /** Finish Reason */
            finish_reason?: string | null;
            /** Model */
            model: string;
            parsed_output?: components["schemas"]["JsonValue"];
            /** Profile Id */
            profile_id: string;
            /** Provider Id */
            provider_id: string;
            usage?: components["schemas"]["ModelUsage"];
        };
        /** ModelUsage */
        ModelUsage: {
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
        };
        /** NpcCandidate */
        NpcCandidate: {
            /** Current Goal */
            current_goal?: string | null;
            /** Id */
            id: string;
            /** Identity */
            identity: string;
            /** Purpose */
            purpose: string;
        };
        /** ProjectCatalogEntry */
        ProjectCatalogEntry: {
            /** Genre */
            genre: string;
            /** Id */
            id: string;
            /** Is Open */
            is_open: boolean;
            /** Title */
            title: string;
            /** World Version */
            world_version: number;
        };
        /** ProjectDocument */
        ProjectDocument: {
            /** Genre */
            genre: string;
            /** Id */
            id: string;
            /**
             * Schema
             * @default project/v1
             * @constant
             */
            schema: "project/v1";
            /** Theme */
            theme: string;
            /** Title */
            title: string;
            /** Tone */
            tone: string;
            /**
             * Version
             * @default 0
             */
            version: number;
        };
        /** ProjectSnapshot */
        ProjectSnapshot: {
            /** Characters */
            characters: components["schemas"]["Character"][];
            /** Facts */
            facts: components["schemas"]["Fact"][];
            project: components["schemas"]["ProjectDocument"];
            world: components["schemas"]["WorldState"];
        };
        /** PromotionAssessment */
        PromotionAssessment: {
            candidate?: components["schemas"]["PromotionCandidate"] | null;
            /** Character Id */
            character_id: string;
            /** Project Id */
            project_id: string;
            review: components["schemas"]["ReviewResult"];
        };
        /** PromotionCandidate */
        PromotionCandidate: {
            /** Base Character Version */
            base_character_version: number;
            /** Base Workspace Revision */
            base_workspace_revision?: string | null;
            /** Character Id */
            character_id: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Proposed Goal */
            proposed_goal: string;
            review: components["schemas"]["ReviewResult"];
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "committed";
        };
        /** PromotionCommitResult */
        PromotionCommitResult: {
            candidate: components["schemas"]["PromotionCandidate"];
            character: components["schemas"]["Character"];
            event: components["schemas"]["StoryEvent"];
        };
        /** PromotionConfirmationRequest */
        PromotionConfirmationRequest: {
            /** Candidate Id */
            candidate_id: string;
        };
        /** RagHit */
        RagHit: {
            /** Chunk Id */
            chunk_id: string;
            /** Content */
            content: string;
            /** Heading */
            heading: string;
            /** Permission Scope */
            permission_scope: string;
            /**
             * Retrieval Mode
             * @enum {string}
             */
            retrieval_mode: "exact" | "bm25";
            /** Score */
            score: number;
            /** Source Id */
            source_id: string;
            /** Source Path */
            source_path: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "project" | "world" | "character" | "event" | "fact" | "scene" | "source";
        };
        /** RagIndexSummary */
        RagIndexSummary: {
            /** Chunk Count */
            chunk_count: number;
            /** Document Count */
            document_count: number;
            /** Fingerprint */
            fingerprint: string;
            /** Project Id */
            project_id: string;
        };
        /** RagSearchRequest */
        RagSearchRequest: {
            /** Exact Id */
            exact_id?: string | null;
            /**
             * Limit
             * @default 8
             */
            limit: number;
            /**
             * Query
             * @default
             */
            query: string;
            scope: components["schemas"]["RetrievalScope"];
        };
        /** RagSearchResult */
        RagSearchResult: {
            /** Exact Id */
            exact_id?: string | null;
            /** Hits */
            hits: components["schemas"]["RagHit"][];
            /** Index Fingerprint */
            index_fingerprint: string;
            /** Permission Scope */
            permission_scope: string;
            /** Query */
            query: string;
        };
        /** Relationship */
        Relationship: {
            /** Character Id */
            character_id: string;
            /** Description */
            description: string;
        };
        /** RetrievalEvidence */
        RetrievalEvidence: {
            /** Chunk Id */
            chunk_id: string;
            /** Content */
            content: string;
            /** Heading */
            heading: string;
            /** Permission Scope */
            permission_scope: string;
            /**
             * Retrieval Mode
             * @enum {string}
             */
            retrieval_mode: "exact" | "bm25";
            /** Score */
            score: number;
            /** Source Id */
            source_id: string;
            /** Source Path */
            source_path: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "project" | "world" | "character" | "event" | "fact" | "scene" | "source";
            /**
             * Task
             * @enum {string}
             */
            task: "writer" | "editor";
        };
        /** RetrievalScope */
        RetrievalScope: {
            /** Character Id */
            character_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "editorial" | "writer" | "character";
        };
        /** ReviewIssue */
        ReviewIssue: {
            /** Code */
            code: string;
            /**
             * Evidence Ids
             * @default []
             */
            evidence_ids: string[];
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "blocking";
        };
        /** ReviewResult */
        ReviewResult: {
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["ReviewIssue"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "submission_review" | "character_review" | "world_review" | "turn_review" | "promotion_review" | "manuscript_review";
            /** Passed */
            passed: boolean;
            /** Summary */
            summary: string;
        };
        /** RevisionRequest */
        RevisionRequest: {
            /** Instruction */
            instruction: string;
        };
        /** Scene */
        Scene: {
            /** Body */
            body: string;
            /** Chapter Id */
            chapter_id: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Sequence */
            sequence: number;
            /** Source Event Ids */
            source_event_ids: string[];
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** SceneDraft */
        SceneDraft: {
            /** Amendment Id */
            amendment_id?: string | null;
            /**
             * Base Scene Version
             * @default 0
             */
            base_scene_version: number;
            /** Base Workspace Revision */
            base_workspace_revision?: string | null;
            /** Base World Version */
            base_world_version: number;
            /** Body */
            body: string;
            /** Chapter Id */
            chapter_id: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Retrieval Evidence
             * @default []
             */
            retrieval_evidence: components["schemas"]["RetrievalEvidence"][];
            review?: components["schemas"]["ManuscriptReviewOutput"] | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Sequence */
            sequence: number;
            /** Source Event Ids */
            source_event_ids: string[];
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "draft" | "reviewed" | "needs_revision" | "amendment_required" | "saved";
            /** Title */
            title: string;
        };
        /** SceneGenerationRequest */
        SceneGenerationRequest: {
            /** Chapter Id */
            chapter_id: string;
            /** Event Ids */
            event_ids: string[];
        };
        /** SceneMutationResult */
        SceneMutationResult: {
            amendment?: components["schemas"]["EventAmendmentCandidate"] | null;
            draft: components["schemas"]["SceneDraft"];
            review: components["schemas"]["ManuscriptReviewOutput"];
            scene?: components["schemas"]["Scene"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "saved" | "amendment_required" | "rejected";
        };
        /** SceneUpdateRequest */
        SceneUpdateRequest: {
            /** Body */
            body: string;
            /** Expected Revision */
            expected_revision: number;
            /** Expected Scene Version */
            expected_scene_version: number;
            /** Title */
            title: string;
        };
        /** StateChange */
        StateChange: {
            /** Field */
            field: string;
            new_value: components["schemas"]["JsonValue"];
            old_value?: components["schemas"]["JsonValue"];
            /** Reason */
            reason: string;
            /** Target Id */
            target_id: string;
            /**
             * Target Type
             * @enum {string}
             */
            target_type: "character" | "world";
        };
        /** StatusResponse */
        StatusResponse: {
            /** Status */
            status: string;
        };
        /** StoryEvent */
        StoryEvent: {
            /** Approved By User */
            approved_by_user: boolean;
            /**
             * Character Changes
             * @default []
             */
            character_changes: components["schemas"]["StateChange"][];
            /**
             * Fact Ids
             * @default []
             */
            fact_ids: string[];
            /** Id */
            id: string;
            /**
             * Knowledge Changes
             * @default []
             */
            knowledge_changes: components["schemas"]["KnowledgeChange"][];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Participants */
            participants: string[];
            /** Sequence */
            sequence: number;
            /** Source Turn Id */
            source_turn_id: string;
            /** Summary */
            summary: string;
            /**
             * World Changes
             * @default []
             */
            world_changes: components["schemas"]["StateChange"][];
        };
        /** SubmissionCharacter */
        SubmissionCharacter: {
            /** Core Desire */
            core_desire: string;
            /** Current Goal */
            current_goal: string;
            /** Display Name */
            display_name: string;
            /** Emotional State */
            emotional_state?: string | null;
            /** Id */
            id: string;
            /** Identity */
            identity: string;
            /**
             * Known Fact Ids
             * @description Only private or secret fact ids belong here. A fact id must appear exactly for the characters listed in that fact's known_by array; never include public fact ids.
             */
            known_fact_ids: string[];
            /** Location */
            location: string;
            /**
             * Resources
             * @default []
             */
            resources: string[];
        };
        /** SubmissionConversationRequest */
        SubmissionConversationRequest: {
            draft: components["schemas"]["SubmissionDraft"];
            /** Messages */
            messages: components["schemas"]["Message"][];
        };
        /** SubmissionConversationResponse */
        SubmissionConversationResponse: {
            draft: components["schemas"]["SubmissionDraft"];
            /** Missing Requirements */
            missing_requirements: string[];
            /** Reply */
            reply: string;
            review: components["schemas"]["ReviewResult"];
            /** Runnable */
            runnable: boolean;
        };
        /**
         * SubmissionDraft
         * @description Non-canonical setting package assembled during submission discussion.
         */
        SubmissionDraft: {
            /**
             * Characters
             * @default []
             */
            characters: components["schemas"]["SubmissionCharacter"][];
            /**
             * Facts
             * @default []
             */
            facts: components["schemas"]["FactCandidate"][];
            /**
             * Genre
             * @default
             */
            genre: string;
            /** Id */
            id: string;
            /**
             * Initial Incident
             * @default
             */
            initial_incident: string;
            /**
             * Initial Location
             * @default
             */
            initial_location: string;
            /**
             * Initial Time
             * @default
             */
            initial_time: string;
            /**
             * Pressures
             * @default []
             */
            pressures: string[];
            /**
             * Theme
             * @default
             */
            theme: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Tone
             * @default
             */
            tone: string;
            /**
             * World Rules
             * @default []
             */
            world_rules: string[];
        };
        /** SubmissionPackage */
        SubmissionPackage: {
            /** Characters */
            characters: components["schemas"]["SubmissionCharacter"][];
            /** Facts */
            facts: components["schemas"]["FactCandidate"][];
            /** Genre */
            genre: string;
            /** Id */
            id: string;
            /** Initial Incident */
            initial_incident: string;
            /** Initial Location */
            initial_location: string;
            /** Initial Time */
            initial_time: string;
            /**
             * Pressures
             * @default []
             */
            pressures: string[];
            /** Theme */
            theme: string;
            /** Title */
            title: string;
            /** Tone */
            tone: string;
            /** World Rules */
            world_rules: string[];
        };
        /** TurnCancellationResult */
        TurnCancellationResult: {
            /**
             * Cancel Requested
             * @default true
             */
            cancel_requested: boolean;
            /** Project Id */
            project_id: string;
            /** Turn Id */
            turn_id?: string | null;
        };
        /** TurnCandidate */
        TurnCandidate: {
            /** Base Character Versions */
            base_character_versions: {
                [key: string]: number;
            };
            /** Base Workspace Revision */
            base_workspace_revision?: string | null;
            /** Base World Version */
            base_world_version: number;
            /** Id */
            id: string;
            /** Intents */
            intents: components["schemas"]["CharacterIntent"][];
            outcome: components["schemas"]["WorldOutcome"];
            /** Project Id */
            project_id: string;
            review?: components["schemas"]["ReviewResult"] | null;
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "draft" | "reviewed" | "needs_revision" | "approved" | "discarded" | "committed";
        };
        /** TurnGenerationRequest */
        TurnGenerationRequest: {
            /**
             * Participant Ids
             * @default []
             */
            participant_ids: string[];
        };
        /** UsageTotals */
        UsageTotals: {
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Requests
             * @default 0
             */
            requests: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceClosedState */
        WorkspaceClosedState: {
            /** Project Id */
            project_id: string;
            /**
             * Status
             * @default closed
             * @constant
             */
            status: "closed";
        };
        /** WorkspaceDocumentEntry */
        WorkspaceDocumentEntry: {
            /** Document Id */
            document_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "project" | "world" | "character" | "event" | "fact" | "scene";
            /** Relative Path */
            relative_path: string;
            /** Sha256 */
            sha256: string;
            /** Version */
            version?: number | null;
        };
        /** WorkspaceIndex */
        WorkspaceIndex: {
            /** Character Versions */
            character_versions: {
                [key: string]: number;
            };
            /** Documents */
            documents: components["schemas"]["WorkspaceDocumentEntry"][];
            /** Event Ids */
            event_ids: string[];
            /** Fact Ids */
            fact_ids: string[];
            /** Project Id */
            project_id: string;
            /** Revision */
            revision: string;
            /** Scene Ids */
            scene_ids: string[];
            /** World Version */
            world_version: number;
        };
        /** WorkspaceState */
        WorkspaceState: {
            index: components["schemas"]["WorkspaceIndex"];
            /** Last Error */
            last_error?: string | null;
            project: components["schemas"]["ProjectSnapshot"];
            /** Recovered Transactions */
            recovered_transactions: number;
            /**
             * Status
             * @default open
             * @constant
             */
            status: "open";
        };
        /** WorldOutcome */
        WorldOutcome: {
            /**
             * Character Changes
             * @default []
             */
            character_changes: components["schemas"]["StateChange"][];
            /**
             * Fact Candidates
             * @default []
             */
            fact_candidates: components["schemas"]["FactCandidate"][];
            /**
             * Knowledge Changes
             * @default []
             */
            knowledge_changes: components["schemas"]["KnowledgeChange"][];
            /**
             * New Npcs
             * @default []
             */
            new_npcs: components["schemas"]["NpcCandidate"][];
            /** Summary */
            summary: string;
            /**
             * Unresolved Consequences
             * @default []
             */
            unresolved_consequences: string[];
            /**
             * World Changes
             * @default []
             */
            world_changes: components["schemas"]["StateChange"][];
        };
        /** WorldState */
        WorldState: {
            /**
             * Active Pressures
             * @default []
             */
            active_pressures: string[];
            /** Current Location */
            current_location?: string | null;
            /** Current Time */
            current_time: string;
            /**
             * Public Fact Ids
             * @default []
             */
            public_fact_ids: string[];
            /**
             * Rules
             * @default []
             */
            rules: string[];
            /**
             * Version
             * @default 0
             */
            version: number;
            /** World Variables */
            world_variables?: {
                [key: string]: string | number | boolean | null;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    engine_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_model_catalog_models_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalog"];
                };
            };
        };
    };
    complete_model_models_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_profiles_models_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProfile"][];
                };
            };
        };
    };
    put_model_profile_models_profiles__profile_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_model_models_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_usage_models_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageTotals"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCatalogEntry"][];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_characters_projects__project_id__characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_character_projects__project_id__characters__character_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_promotion_projects__project_id__characters__character_id__promote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromotionConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionCommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_promotion_projects__project_id__characters__character_id__promotion_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionAssessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_project_projects__project_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceClosedState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_projects__project_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_manuscript_projects__project_id__manuscript_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManuscriptExport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_project_projects__project_id__open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_index_projects__project_id__rag_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagIndexSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_projects__project_id__rag_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenes_projects__project_id__scenes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneDraft"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_scene_projects__project_id__scenes_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scene_projects__project_id__scenes__scene_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scene_projects__project_id__scenes__scene_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneMutationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_amendment_projects__project_id__scenes__scene_id__amendments__amendment_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                scene_id: string;
                amendment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AmendmentCommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discuss_submission_projects__project_id__submission_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_active_turn_projects__project_id__turns_active_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnCancellationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_turn_projects__project_id__turns_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_turn_projects__project_id__turns__turn_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_turn_projects__project_id__turns__turn_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_turn_projects__project_id__turns__turn_id__discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_turn_revision_projects__project_id__turns__turn_id__request_revision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                turn_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_projects__project_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_submission_submissions_finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionPackage"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
