/* eslint-disable */
// Generated by pnpm contracts:generate. Do not edit manually.
export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Engine Status */
        get: operations["engine_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Catalog */
        get: operations["get_model_catalog_models_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Model */
        post: operations["complete_model_models_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Profiles */
        get: operations["get_model_profiles_models_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Model Profile */
        put: operations["put_model_profile_models_profiles__profile_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Model */
        post: operations["stream_model_models_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Usage */
        get: operations["model_usage_models_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Branch */
        post: operations["create_branch_projects__project_id__branches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/branches/{branch_id}/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild Projection */
        post: operations["rebuild_projection_projects__project_id__branches__branch_id__projection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/branches/{branch_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback Branch */
        post: operations["rollback_branch_projects__project_id__branches__branch_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Characters */
        get: operations["list_characters_projects__project_id__characters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Character */
        get: operations["get_character_projects__project_id__characters__character_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/characters/{character_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Promotion */
        post: operations["confirm_promotion_projects__project_id__characters__character_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/characters/{character_id}/promotion-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Promotion */
        post: operations["review_promotion_projects__project_id__characters__character_id__promotion_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Project */
        post: operations["close_project_projects__project_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_projects__project_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/manuscript/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Manuscript */
        get: operations["export_manuscript_projects__project_id__manuscript_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Project */
        post: operations["open_project_projects__project_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/rag/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild Index */
        post: operations["rebuild_index_projects__project_id__rag_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/rag/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_projects__project_id__rag_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenes */
        get: operations["list_scenes_projects__project_id__scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/scenes/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Scene */
        post: operations["generate_scene_projects__project_id__scenes_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/scenes/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scene */
        get: operations["get_scene_projects__project_id__scenes__scene_id__get"];
        /** Update Scene */
        put: operations["update_scene_projects__project_id__scenes__scene_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/scenes/{scene_id}/amendments/{amendment_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Amendment */
        post: operations["confirm_amendment_projects__project_id__scenes__scene_id__amendments__amendment_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Simulation */
        post: operations["start_simulation_projects__project_id__simulations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/simulations/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Simulation */
        get: operations["get_simulation_projects__project_id__simulations__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/simulations/{session_id}/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkpoint Simulation */
        post: operations["checkpoint_simulation_projects__project_id__simulations__session_id__checkpoint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/simulations/{session_id}/locale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch Simulation Locale */
        post: operations["switch_simulation_locale_projects__project_id__simulations__session_id__locale_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/simulations/{session_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Simulation */
        post: operations["pause_simulation_projects__project_id__simulations__session_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/simulations/{session_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Simulation */
        post: operations["resume_simulation_projects__project_id__simulations__session_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/simulations/{session_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Simulation */
        post: operations["run_simulation_projects__project_id__simulations__session_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/simulations/{session_id}/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Step Simulation */
        post: operations["step_simulation_projects__project_id__simulations__session_id__step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/simulations/{session_id}/terminate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Terminate Simulation */
        post: operations["terminate_simulation_projects__project_id__simulations__session_id__terminate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/submission/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discuss Submission */
        post: operations["discuss_submission_projects__project_id__submission_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_projects__project_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Submission */
        post: operations["finalize_submission_submissions_finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionOutputType
         * @enum {string}
         */
        ActionOutputType: "free" | "choice" | "float" | "make_observation" | "next_acting" | "next_action_spec" | "resolve" | "terminate" | "next_game_master" | "skip_this_step";
        /**
         * ActionSpec
         * @description Serializable project-side equivalent of Concordia's ActionSpec.
         */
        ActionSpec: {
            action_kind?: components["schemas"]["StoryActionKind"] | null;
            /** Call To Action */
            call_to_action: string;
            /** Content Locale */
            content_locale: string;
            /** Metadata */
            metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Option Ids
             * @default []
             */
            option_ids: string[];
            /**
             * Options
             * @default []
             */
            options: string[];
            output_type: components["schemas"]["ActionOutputType"];
            /** Spec Id */
            spec_id: string;
            /** Tag */
            tag?: string | null;
        };
        /** AmendmentCommitResult */
        AmendmentCommitResult: {
            amendment: components["schemas"]["EventAmendmentCandidate"];
            event: components["schemas"]["StoryEvent"];
            scene: components["schemas"]["Scene"];
        };
        /** BranchCreateRequest */
        BranchCreateRequest: {
            /** Branch Id */
            branch_id: string;
            /**
             * Content Locale
             * @default zh-CN
             */
            content_locale: string;
            /**
             * Parent Branch Id
             * @default main
             */
            parent_branch_id: string;
            /** Source Checkpoint Id */
            source_checkpoint_id: string;
        };
        /** BranchManifest */
        BranchManifest: {
            /** Branch Id */
            branch_id: string;
            /** Content Locale */
            content_locale: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fork Checkpoint Id */
            fork_checkpoint_id?: string | null;
            /** Head Checkpoint Id */
            head_checkpoint_id?: string | null;
            /**
             * Head Step
             * @default 0
             */
            head_step: number;
            /** Parent Branch Id */
            parent_branch_id?: string | null;
            /** Project Id */
            project_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BranchRollbackRequest */
        BranchRollbackRequest: {
            /** Checkpoint Id */
            checkpoint_id: string;
        };
        /** Character */
        Character: {
            /** Core Desire */
            core_desire: string;
            /** Current Goal */
            current_goal?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Emotional State */
            emotional_state?: string | null;
            /** Id */
            id: string;
            /** Identity */
            identity: string;
            /**
             * Known Fact Ids
             * @default []
             */
            known_fact_ids: string[];
            /** Last Event Id */
            last_event_id?: string | null;
            /** Location */
            location?: string | null;
            /**
             * Relationships
             * @default []
             */
            relationships: components["schemas"]["Relationship"][];
            /**
             * Resources
             * @default []
             */
            resources: string[];
            /**
             * Type
             * @enum {string}
             */
            type: "active" | "npc" | "retired";
            /**
             * Version
             * @default 0
             */
            version: number;
        };
        /** CheckpointRequest */
        CheckpointRequest: {
            /**
             * Reason
             * @default user checkpoint
             */
            reason: string;
        };
        /** CommitResult */
        CommitResult: {
            branch: components["schemas"]["BranchManifest"];
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Session Id */
            session_id: string;
            /** State Hash */
            state_hash: string;
            /** Step */
            step: number;
            /** Written Paths */
            written_paths: string[];
        };
        /**
         * ControlMode
         * @enum {string}
         */
        ControlMode: "step" | "scene" | "chapter" | "autonomous";
        /** ControlPolicy */
        ControlPolicy: {
            /**
             * Allow Dynamic Entities
             * @default true
             */
            allow_dynamic_entities: boolean;
            /**
             * Allow User Override
             * @default true
             */
            allow_user_override: boolean;
            /**
             * Checkpoint Every Steps
             * @default 1
             */
            checkpoint_every_steps: number;
            /**
             * Max Consecutive Model Failures
             * @default 3
             */
            max_consecutive_model_failures: number;
            /**
             * Max Runtime Seconds
             * @default 3600
             */
            max_runtime_seconds: number;
            /**
             * Max Scenes
             * @default 1
             */
            max_scenes: number;
            /**
             * Max Steps
             * @default 40
             */
            max_steps: number;
            /**
             * Max Total Tokens
             * @default 500000
             */
            max_total_tokens: number;
            mode: components["schemas"]["ControlMode"];
            /**
             * Pause After Scene
             * @default true
             */
            pause_after_scene: boolean;
            /**
             * Pause After Step
             * @default false
             */
            pause_after_step: boolean;
        };
        /**
         * EffectOperation
         * @enum {string}
         */
        EffectOperation: "set" | "append" | "remove" | "create_entity" | "archive_entity" | "emit_signal";
        /**
         * EffectTarget
         * @enum {string}
         */
        EffectTarget: "world_projection" | "character_projection" | "system";
        /** EventAmendmentCandidate */
        EventAmendmentCandidate: {
            /** Base Workspace Revision */
            base_workspace_revision?: string | null;
            /** Base World Version */
            base_world_version: number;
            /** Draft Revision */
            draft_revision: number;
            /** Fact Ids */
            fact_ids: string[];
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Proposed Facts */
            proposed_facts: string[];
            /** Scene Id */
            scene_id: string;
            /** Source Event Ids */
            source_event_ids: string[];
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "committed";
        };
        /**
         * EventVisibility
         * @enum {string}
         */
        EventVisibility: "public" | "participants" | "restricted" | "gm_only";
        /** Fact */
        Fact: {
            /** Id */
            id: string;
            /**
             * Introduced At
             * Format: date-time
             */
            introduced_at: string;
            /**
             * Known By
             * @default []
             */
            known_by: string[];
            /** Source Event Id */
            source_event_id: string;
            /** Statement */
            statement: string;
            /** Supersedes Fact Id */
            supersedes_fact_id?: string | null;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "public" | "private" | "secret";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** InitialFact */
        InitialFact: {
            /** Id */
            id: string;
            /**
             * Known By
             * @description Must be empty when visibility is public. For private or secret facts, list every knowing character id exactly once.
             * @default []
             */
            known_by: string[];
            /** Statement */
            statement: string;
            /** Supersedes Fact Id */
            supersedes_fact_id?: string | null;
            /**
             * Visibility
             * @description Use public for facts known to everyone. Use private or secret only when knowledge is restricted to specific characters.
             * @enum {string}
             */
            visibility: "public" | "private" | "secret";
        };
        JsonValue: unknown;
        /** KnowledgeChange */
        KnowledgeChange: {
            /**
             * Action
             * @enum {string}
             */
            action: "learn" | "forget";
            /** Character Id */
            character_id: string;
            /** Fact Id */
            fact_id: string;
            /** Reason */
            reason: string;
        };
        /** ManuscriptExport */
        ManuscriptExport: {
            /** Filename */
            filename: string;
            /** Markdown */
            markdown: string;
        };
        /** ManuscriptReviewOutput */
        ManuscriptReviewOutput: {
            /**
             * New Facts
             * @default []
             */
            new_facts: string[];
            review: components["schemas"]["ReviewResult"];
        };
        /**
         * MemoryScope
         * @enum {string}
         */
        MemoryScope: "game_master" | "character" | "shared";
        /** MemorySnapshot */
        MemorySnapshot: {
            /** Owner Id */
            owner_id: string;
            /** Record Count */
            record_count: number;
            scope: components["schemas"]["MemoryScope"];
            /** State */
            state: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** State Hash */
            state_hash: string;
        };
        /** Message */
        Message: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant";
        };
        /** ModelCatalog */
        ModelCatalog: {
            /** Profiles */
            profiles: components["schemas"]["ModelProfile"][];
        };
        /** ModelProfile */
        ModelProfile: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Id */
            id: string;
            /**
             * Max Output Tokens
             * @default 2048
             */
            max_output_tokens: number;
            /** Model */
            model: string;
            /** Name */
            name: string;
            /** Provider Id */
            provider_id: string;
            /**
             * Reasoning Effort
             * @default disabled
             * @enum {string}
             */
            reasoning_effort: "disabled" | "low" | "high" | "max";
            /**
             * Task Type
             * @enum {string}
             */
            task_type: "actor" | "game_master" | "reflection" | "memory_consolidation" | "projection" | "editor" | "writer" | "embedding";
            /** Temperature */
            temperature?: number | null;
            /**
             * Timeout Seconds
             * @default 60
             */
            timeout_seconds: number;
        };
        /** ModelRequest */
        ModelRequest: {
            /** Max Output Tokens */
            max_output_tokens: number;
            /** Messages */
            messages: components["schemas"]["Message"][];
            /** Output Schema */
            output_schema?: string | null;
            /** Profile Id */
            profile_id: string;
            /**
             * Task Type
             * @enum {string}
             */
            task_type: "actor" | "game_master" | "reflection" | "memory_consolidation" | "projection" | "editor" | "writer" | "embedding";
            /** Temperature */
            temperature?: number | null;
            /** Timeout Seconds */
            timeout_seconds: number;
        };
        /** ModelResponse */
        ModelResponse: {
            /** Content */
            content: string;
            /** Finish Reason */
            finish_reason?: string | null;
            /** Model */
            model: string;
            parsed_output?: components["schemas"]["JsonValue"];
            /** Profile Id */
            profile_id: string;
            /** Provider Id */
            provider_id: string;
            usage?: components["schemas"]["ModelUsage"];
        };
        /** ModelUsage */
        ModelUsage: {
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
        };
        /** ProjectCatalogEntry */
        ProjectCatalogEntry: {
            /** Genre */
            genre: string;
            /** Id */
            id: string;
            /** Is Open */
            is_open: boolean;
            /** Title */
            title: string;
            /** World Version */
            world_version: number;
        };
        /** ProjectDocument */
        ProjectDocument: {
            /** Genre */
            genre: string;
            /** Id */
            id: string;
            /**
             * Schema
             * @default project/v1
             * @constant
             */
            schema: "project/v1";
            /** Theme */
            theme: string;
            /** Title */
            title: string;
            /** Tone */
            tone: string;
            /**
             * Version
             * @default 0
             */
            version: number;
        };
        /** ProjectSnapshot */
        ProjectSnapshot: {
            /** Characters */
            characters: components["schemas"]["Character"][];
            /** Facts */
            facts: components["schemas"]["Fact"][];
            project: components["schemas"]["ProjectDocument"];
            world: components["schemas"]["WorldState"];
        };
        /** ProjectionRequest */
        ProjectionRequest: {
            /** Checkpoint Id */
            checkpoint_id?: string | null;
        };
        /** ProjectionResponse */
        ProjectionResponse: {
            /** Branch Id */
            branch_id: string;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Written Paths */
            written_paths: string[];
        };
        /** PromotionAssessment */
        PromotionAssessment: {
            candidate?: components["schemas"]["PromotionCandidate"] | null;
            /** Character Id */
            character_id: string;
            /** Project Id */
            project_id: string;
            review: components["schemas"]["ReviewResult"];
        };
        /** PromotionCandidate */
        PromotionCandidate: {
            /** Base Character Version */
            base_character_version: number;
            /** Base Workspace Revision */
            base_workspace_revision?: string | null;
            /** Character Id */
            character_id: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Proposed Goal */
            proposed_goal: string;
            review: components["schemas"]["ReviewResult"];
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "committed";
        };
        /** PromotionCommitResult */
        PromotionCommitResult: {
            candidate: components["schemas"]["PromotionCandidate"];
            character: components["schemas"]["Character"];
            event: components["schemas"]["StoryEvent"];
        };
        /** PromotionConfirmationRequest */
        PromotionConfirmationRequest: {
            /** Candidate Id */
            candidate_id: string;
        };
        /** RagHit */
        RagHit: {
            /** Chunk Id */
            chunk_id: string;
            /** Content */
            content: string;
            /** Heading */
            heading: string;
            /** Permission Scope */
            permission_scope: string;
            /**
             * Retrieval Mode
             * @enum {string}
             */
            retrieval_mode: "exact" | "bm25";
            /** Score */
            score: number;
            /** Source Id */
            source_id: string;
            /** Source Path */
            source_path: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "project" | "world" | "character" | "event" | "fact" | "scene" | "source";
        };
        /** RagIndexSummary */
        RagIndexSummary: {
            /** Chunk Count */
            chunk_count: number;
            /** Document Count */
            document_count: number;
            /** Fingerprint */
            fingerprint: string;
            /** Project Id */
            project_id: string;
        };
        /** RagSearchRequest */
        RagSearchRequest: {
            /** Exact Id */
            exact_id?: string | null;
            /**
             * Limit
             * @default 8
             */
            limit: number;
            /**
             * Query
             * @default
             */
            query: string;
            scope: components["schemas"]["RetrievalScope"];
        };
        /** RagSearchResult */
        RagSearchResult: {
            /** Exact Id */
            exact_id?: string | null;
            /** Hits */
            hits: components["schemas"]["RagHit"][];
            /** Index Fingerprint */
            index_fingerprint: string;
            /** Permission Scope */
            permission_scope: string;
            /** Query */
            query: string;
        };
        /** Relationship */
        Relationship: {
            /** Character Id */
            character_id: string;
            /** Description */
            description: string;
        };
        /**
         * ResolvedEvent
         * @description Lightweight projection of a Game Master world event.
         */
        ResolvedEvent: {
            /** Actor Id */
            actor_id?: string | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Content Locale */
            content_locale: string;
            /**
             * Effects
             * @default []
             */
            effects: components["schemas"]["StateEffect"][];
            /** Event Id */
            event_id: string;
            /** Event Text */
            event_text: string;
            /**
             * Importance
             * @default 0.5
             */
            importance: number;
            /**
             * Location Ids
             * @default []
             */
            location_ids: string[];
            /**
             * Observer Ids
             * @default []
             */
            observer_ids: string[];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Participant Ids
             * @default []
             */
            participant_ids: string[];
            /** Session Id */
            session_id: string;
            /**
             * Source Intent Ids
             * @default []
             */
            source_intent_ids: string[];
            /**
             * Source Memory Ids
             * @default []
             */
            source_memory_ids: string[];
            /** Step */
            step: number;
            visibility: components["schemas"]["EventVisibility"];
        };
        /**
         * ResolvedTurn
         * @description Project-side projection of one Engine step.
         */
        ResolvedTurn: {
            /** Acting Actor Id */
            acting_actor_id?: string | null;
            action_spec?: components["schemas"]["ActionSpec"] | null;
            /** Branch Id */
            branch_id: string;
            /** Content Locale */
            content_locale: string;
            /**
             * Effects
             * @default []
             */
            effects: components["schemas"]["StateEffect"][];
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["ResolvedEvent"][];
            /** Putative Event Text */
            putative_event_text?: string | null;
            /** Raw Resolution Text */
            raw_resolution_text: string;
            /** Session Id */
            session_id: string;
            /** Step */
            step: number;
            /**
             * Terminated
             * @default false
             */
            terminated: boolean;
            /** Termination Reason Text */
            termination_reason_text?: string | null;
        };
        /** RetrievalEvidence */
        RetrievalEvidence: {
            /** Chunk Id */
            chunk_id: string;
            /** Content */
            content: string;
            /** Heading */
            heading: string;
            /** Permission Scope */
            permission_scope: string;
            /**
             * Retrieval Mode
             * @enum {string}
             */
            retrieval_mode: "exact" | "bm25";
            /** Score */
            score: number;
            /** Source Id */
            source_id: string;
            /** Source Path */
            source_path: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "project" | "world" | "character" | "event" | "fact" | "scene" | "source";
            /**
             * Task
             * @enum {string}
             */
            task: "writer" | "editor";
        };
        /** RetrievalScope */
        RetrievalScope: {
            /** Character Id */
            character_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "editorial" | "writer" | "character";
        };
        /** ReviewIssue */
        ReviewIssue: {
            /** Code */
            code: string;
            /**
             * Evidence Ids
             * @default []
             */
            evidence_ids: string[];
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "blocking";
        };
        /** ReviewResult */
        ReviewResult: {
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["ReviewIssue"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "submission_review" | "character_review" | "world_review" | "promotion_review" | "manuscript_review";
            /** Passed */
            passed: boolean;
            /** Summary */
            summary: string;
        };
        /** Scene */
        Scene: {
            /** Body */
            body: string;
            /** Chapter Id */
            chapter_id: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Sequence */
            sequence: number;
            /** Source Event Ids */
            source_event_ids: string[];
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** SceneDraft */
        SceneDraft: {
            /** Amendment Id */
            amendment_id?: string | null;
            /**
             * Base Scene Version
             * @default 0
             */
            base_scene_version: number;
            /** Base Workspace Revision */
            base_workspace_revision?: string | null;
            /** Base World Version */
            base_world_version: number;
            /** Body */
            body: string;
            /** Chapter Id */
            chapter_id: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Retrieval Evidence
             * @default []
             */
            retrieval_evidence: components["schemas"]["RetrievalEvidence"][];
            review?: components["schemas"]["ManuscriptReviewOutput"] | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Sequence */
            sequence: number;
            /** Source Event Ids */
            source_event_ids: string[];
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "draft" | "reviewed" | "needs_revision" | "amendment_required" | "saved";
            /** Title */
            title: string;
        };
        /** SceneGenerationRequest */
        SceneGenerationRequest: {
            /** Chapter Id */
            chapter_id: string;
            /** Event Ids */
            event_ids: string[];
        };
        /** SceneMutationResult */
        SceneMutationResult: {
            amendment?: components["schemas"]["EventAmendmentCandidate"] | null;
            draft: components["schemas"]["SceneDraft"];
            review: components["schemas"]["ManuscriptReviewOutput"];
            scene?: components["schemas"]["Scene"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "saved" | "amendment_required" | "rejected";
        };
        /** SceneUpdateRequest */
        SceneUpdateRequest: {
            /** Body */
            body: string;
            /** Expected Revision */
            expected_revision: number;
            /** Expected Scene Version */
            expected_scene_version: number;
            /** Title */
            title: string;
        };
        /** SimulationLocaleRequest */
        SimulationLocaleRequest: {
            /** Content Locale */
            content_locale: string;
        };
        /** SimulationStartRequest */
        SimulationStartRequest: {
            /**
             * Actor Ids
             * @default []
             */
            actor_ids: string[];
            /**
             * Branch Id
             * @default main
             */
            branch_id: string;
            /**
             * Content Locale
             * @default zh-CN
             */
            content_locale: string;
            control: components["schemas"]["ControlPolicy"];
            /** Premise Text */
            premise_text: string;
            /** Seed */
            seed?: number | null;
        };
        /** SimulationTerminateRequest */
        SimulationTerminateRequest: {
            /** Reason Text */
            reason_text: string;
        };
        /** StateChange */
        StateChange: {
            /** Field */
            field: string;
            new_value: components["schemas"]["JsonValue"];
            old_value?: components["schemas"]["JsonValue"];
            /** Reason */
            reason: string;
            /** Target Id */
            target_id: string;
            /**
             * Target Type
             * @enum {string}
             */
            target_type: "character" | "world";
        };
        /**
         * StateEffect
         * @description Optional machine projection; natural-language events remain authoritative.
         */
        StateEffect: {
            after?: components["schemas"]["JsonValue"];
            before?: components["schemas"]["JsonValue"];
            /** Effect Id */
            effect_id: string;
            operation: components["schemas"]["EffectOperation"];
            /** Path */
            path?: string | null;
            /** Reason Text */
            reason_text?: string | null;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /**
             * Source Record Ids
             * @default []
             */
            source_record_ids: string[];
            target: components["schemas"]["EffectTarget"];
            /** Target Id */
            target_id?: string | null;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Status */
            status: string;
        };
        /** StepResult */
        StepResult: {
            /** Acting Actor Id */
            acting_actor_id: string | null;
            action_spec: components["schemas"]["ActionSpec"] | null;
            /** Action Text */
            action_text: string | null;
            /** Branch Id */
            branch_id: string;
            /** Checkpoint Id */
            checkpoint_id?: string | null;
            resolved_turn: components["schemas"]["ResolvedTurn"] | null;
            /** Session Id */
            session_id: string;
            status: components["schemas"]["TurnSessionStatus"];
            /** Step */
            step: number;
        };
        /**
         * StoryActionKind
         * @enum {string}
         */
        StoryActionKind: "free_action" | "dialogue" | "reaction" | "internal_decision" | "choice" | "wait" | "scene_proposal";
        /** StoryEvent */
        StoryEvent: {
            /** Approved By User */
            approved_by_user: boolean;
            /**
             * Character Changes
             * @default []
             */
            character_changes: components["schemas"]["StateChange"][];
            /**
             * Fact Ids
             * @default []
             */
            fact_ids: string[];
            /** Id */
            id: string;
            /**
             * Knowledge Changes
             * @default []
             */
            knowledge_changes: components["schemas"]["KnowledgeChange"][];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Participants */
            participants: string[];
            /** Sequence */
            sequence: number;
            /** Source Record Id */
            source_record_id: string;
            /** Summary */
            summary: string;
            /**
             * World Changes
             * @default []
             */
            world_changes: components["schemas"]["StateChange"][];
        };
        /** SubmissionCharacter */
        SubmissionCharacter: {
            /** Core Desire */
            core_desire: string;
            /** Current Goal */
            current_goal: string;
            /** Display Name */
            display_name: string;
            /** Emotional State */
            emotional_state?: string | null;
            /** Id */
            id: string;
            /** Identity */
            identity: string;
            /**
             * Known Fact Ids
             * @description Only private or secret fact ids belong here. A fact id must appear exactly for the characters listed in that fact's known_by array; never include public fact ids.
             */
            known_fact_ids: string[];
            /** Location */
            location: string;
            /**
             * Resources
             * @default []
             */
            resources: string[];
        };
        /** SubmissionConversationRequest */
        SubmissionConversationRequest: {
            draft: components["schemas"]["SubmissionDraft"];
            /** Messages */
            messages: components["schemas"]["Message"][];
        };
        /** SubmissionConversationResponse */
        SubmissionConversationResponse: {
            draft: components["schemas"]["SubmissionDraft"];
            /** Missing Requirements */
            missing_requirements: string[];
            /** Reply */
            reply: string;
            review: components["schemas"]["ReviewResult"];
            /** Runnable */
            runnable: boolean;
        };
        /**
         * SubmissionDraft
         * @description Non-canonical setting package assembled during submission discussion.
         */
        SubmissionDraft: {
            /**
             * Characters
             * @default []
             */
            characters: components["schemas"]["SubmissionCharacter"][];
            /**
             * Facts
             * @default []
             */
            facts: components["schemas"]["InitialFact"][];
            /**
             * Genre
             * @default
             */
            genre: string;
            /** Id */
            id: string;
            /**
             * Initial Incident
             * @default
             */
            initial_incident: string;
            /**
             * Initial Location
             * @default
             */
            initial_location: string;
            /**
             * Initial Time
             * @default
             */
            initial_time: string;
            /**
             * Pressures
             * @default []
             */
            pressures: string[];
            /**
             * Theme
             * @default
             */
            theme: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Tone
             * @default
             */
            tone: string;
            /**
             * World Rules
             * @default []
             */
            world_rules: string[];
        };
        /** SubmissionPackage */
        SubmissionPackage: {
            /** Characters */
            characters: components["schemas"]["SubmissionCharacter"][];
            /** Facts */
            facts: components["schemas"]["InitialFact"][];
            /** Genre */
            genre: string;
            /** Id */
            id: string;
            /** Initial Incident */
            initial_incident: string;
            /** Initial Location */
            initial_location: string;
            /** Initial Time */
            initial_time: string;
            /**
             * Pressures
             * @default []
             */
            pressures: string[];
            /** Theme */
            theme: string;
            /** Title */
            title: string;
            /** Tone */
            tone: string;
            /** World Rules */
            world_rules: string[];
        };
        /** TurnSessionSnapshot */
        TurnSessionSnapshot: {
            /** Active Actor Id */
            active_actor_id?: string | null;
            /** Actor States */
            actor_states: {
                [key: string]: {
                    [key: string]: components["schemas"]["JsonValue"];
                };
            };
            /** Branch Id */
            branch_id: string;
            /** Checkpoint Id */
            checkpoint_id?: string | null;
            /**
             * Consecutive Model Failures
             * @default 0
             */
            consecutive_model_failures: number;
            /** Content Locale */
            content_locale: string;
            current_action_spec?: components["schemas"]["ActionSpec"] | null;
            /** Current Step */
            current_step: number;
            /** Game Master States */
            game_master_states: {
                [key: string]: {
                    [key: string]: components["schemas"]["JsonValue"];
                };
            };
            /** Memory Snapshots */
            memory_snapshots: {
                [key: string]: components["schemas"]["MemorySnapshot"];
            };
            /** Project Id */
            project_id: string;
            /** Raw Log Offset */
            raw_log_offset: number;
            /** Session Id */
            session_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** State Hash */
            state_hash: string;
            status: components["schemas"]["TurnSessionStatus"];
            /** Termination Reason Text */
            termination_reason_text?: string | null;
            /**
             * Total Model Tokens
             * @default 0
             */
            total_model_tokens: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TurnSessionStatus
         * @enum {string}
         */
        TurnSessionStatus: "created" | "running" | "paused" | "terminated" | "cancelled" | "failed";
        /** UsageTotals */
        UsageTotals: {
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Requests
             * @default 0
             */
            requests: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceClosedState */
        WorkspaceClosedState: {
            /** Project Id */
            project_id: string;
            /**
             * Status
             * @default closed
             * @constant
             */
            status: "closed";
        };
        /** WorkspaceDocumentEntry */
        WorkspaceDocumentEntry: {
            /** Document Id */
            document_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "project" | "world" | "character" | "event" | "fact" | "scene";
            /** Relative Path */
            relative_path: string;
            /** Sha256 */
            sha256: string;
            /** Version */
            version?: number | null;
        };
        /** WorkspaceIndex */
        WorkspaceIndex: {
            /** Character Versions */
            character_versions: {
                [key: string]: number;
            };
            /** Documents */
            documents: components["schemas"]["WorkspaceDocumentEntry"][];
            /** Event Ids */
            event_ids: string[];
            /** Fact Ids */
            fact_ids: string[];
            /** Project Id */
            project_id: string;
            /** Revision */
            revision: string;
            /** Scene Ids */
            scene_ids: string[];
            /** World Version */
            world_version: number;
        };
        /** WorkspaceState */
        WorkspaceState: {
            index: components["schemas"]["WorkspaceIndex"];
            /** Last Error */
            last_error?: string | null;
            project: components["schemas"]["ProjectSnapshot"];
            /** Recovered Transactions */
            recovered_transactions: number;
            /**
             * Status
             * @default open
             * @constant
             */
            status: "open";
        };
        /** WorldState */
        WorldState: {
            /**
             * Active Pressures
             * @default []
             */
            active_pressures: string[];
            /** Current Location */
            current_location?: string | null;
            /** Current Time */
            current_time: string;
            /**
             * Public Fact Ids
             * @default []
             */
            public_fact_ids: string[];
            /**
             * Rules
             * @default []
             */
            rules: string[];
            /**
             * Version
             * @default 0
             */
            version: number;
            /** World Variables */
            world_variables?: {
                [key: string]: string | number | boolean | null;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    engine_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_model_catalog_models_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalog"];
                };
            };
        };
    };
    complete_model_models_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_profiles_models_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProfile"][];
                };
            };
        };
    };
    put_model_profile_models_profiles__profile_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_model_models_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_usage_models_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageTotals"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCatalogEntry"][];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_branch_projects__project_id__branches_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_projection_projects__project_id__branches__branch_id__projection_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                branch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_branch_projects__project_id__branches__branch_id__rollback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                branch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchRollbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_characters_projects__project_id__characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_character_projects__project_id__characters__character_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_promotion_projects__project_id__characters__character_id__promote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromotionConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionCommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_promotion_projects__project_id__characters__character_id__promotion_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionAssessment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_project_projects__project_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceClosedState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_projects__project_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_manuscript_projects__project_id__manuscript_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManuscriptExport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_project_projects__project_id__open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_index_projects__project_id__rag_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagIndexSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_projects__project_id__rag_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenes_projects__project_id__scenes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneDraft"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_scene_projects__project_id__scenes_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scene_projects__project_id__scenes__scene_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scene_projects__project_id__scenes__scene_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneMutationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_amendment_projects__project_id__scenes__scene_id__amendments__amendment_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                scene_id: string;
                amendment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AmendmentCommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_simulation_projects__project_id__simulations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnSessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulation_projects__project_id__simulations__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnSessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkpoint_simulation_projects__project_id__simulations__session_id__checkpoint_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckpointRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_simulation_locale_projects__project_id__simulations__session_id__locale_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationLocaleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnSessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_simulation_projects__project_id__simulations__session_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnSessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_simulation_projects__project_id__simulations__session_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnSessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_simulation_projects__project_id__simulations__session_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnSessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    step_simulation_projects__project_id__simulations__session_id__step_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    terminate_simulation_projects__project_id__simulations__session_id__terminate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationTerminateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnSessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discuss_submission_projects__project_id__submission_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_projects__project_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_submission_submissions_finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionPackage"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
