/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as SubmissionRouteImport } from './routes/submission'
import { Route as ManuscriptRouteImport } from './routes/manuscript'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as EvolveRouteImport } from './routes/evolve'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads/$threadId'
import { Route as SettingsWebSearchRouteImport } from './routes/settings/web-search'
import { Route as SettingsStoryModelsRouteImport } from './routes/settings/story-models'
import { Route as SettingsShortcutsRouteImport } from './routes/settings/shortcuts'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsMcpServersRouteImport } from './routes/settings/mcp-servers'
import { Route as SettingsInterfaceRouteImport } from './routes/settings/interface'
import { Route as SettingsHttpsProxyRouteImport } from './routes/settings/https-proxy'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsExtensionsRouteImport } from './routes/settings/extensions'
import { Route as SettingsAssistantRouteImport } from './routes/settings/assistant'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as SettingsProvidersIndexRouteImport } from './routes/settings/providers/index'
import { Route as SettingsProvidersProviderNameRouteImport } from './routes/settings/providers/$providerName'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionRoute = SubmissionRouteImport.update({
  id: '/submission',
  path: '/submission',
  getParentRoute: () => rootRouteImport,
} as any)
const ManuscriptRoute = ManuscriptRouteImport.update({
  id: '/manuscript',
  path: '/manuscript',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolveRoute = EvolveRouteImport.update({
  id: '/evolve',
  path: '/evolve',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWebSearchRoute = SettingsWebSearchRouteImport.update({
  id: '/settings/web-search',
  path: '/settings/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStoryModelsRoute = SettingsStoryModelsRouteImport.update({
  id: '/settings/story-models',
  path: '/settings/story-models',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: '/settings/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMcpServersRoute = SettingsMcpServersRouteImport.update({
  id: '/settings/mcp-servers',
  path: '/settings/mcp-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInterfaceRoute = SettingsInterfaceRouteImport.update({
  id: '/settings/interface',
  path: '/settings/interface',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHttpsProxyRoute = SettingsHttpsProxyRouteImport.update({
  id: '/settings/https-proxy',
  path: '/settings/https-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExtensionsRoute = SettingsExtensionsRouteImport.update({
  id: '/settings/extensions',
  path: '/settings/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAssistantRoute = SettingsAssistantRouteImport.update({
  id: '/settings/assistant',
  path: '/settings/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersIndexRoute = SettingsProvidersIndexRouteImport.update({
  id: '/settings/providers/',
  path: '/settings/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersProviderNameRoute =
  SettingsProvidersProviderNameRouteImport.update({
    id: '/settings/providers/$providerName',
    path: '/settings/providers/$providerName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/events': typeof EventsRoute
  '/evolve': typeof EvolveRoute
  '/logs': typeof LogsRoute
  '/manuscript': typeof ManuscriptRoute
  '/submission': typeof SubmissionRoute
  '/world': typeof WorldRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/story-models': typeof SettingsStoryModelsRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/events': typeof EventsRoute
  '/evolve': typeof EvolveRoute
  '/logs': typeof LogsRoute
  '/manuscript': typeof ManuscriptRoute
  '/submission': typeof SubmissionRoute
  '/world': typeof WorldRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/story-models': typeof SettingsStoryModelsRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/events': typeof EventsRoute
  '/evolve': typeof EvolveRoute
  '/logs': typeof LogsRoute
  '/manuscript': typeof ManuscriptRoute
  '/submission': typeof SubmissionRoute
  '/world': typeof WorldRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/settings/assistant': typeof SettingsAssistantRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/https-proxy': typeof SettingsHttpsProxyRoute
  '/settings/interface': typeof SettingsInterfaceRoute
  '/settings/mcp-servers': typeof SettingsMcpServersRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/story-models': typeof SettingsStoryModelsRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/events'
    | '/evolve'
    | '/logs'
    | '/manuscript'
    | '/submission'
    | '/world'
    | '/project/$projectId'
    | '/settings/assistant'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/mcp-servers'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/settings/story-models'
    | '/settings/web-search'
    | '/threads/$threadId'
    | '/settings/providers/$providerName'
    | '/settings/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/events'
    | '/evolve'
    | '/logs'
    | '/manuscript'
    | '/submission'
    | '/world'
    | '/project/$projectId'
    | '/settings/assistant'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/mcp-servers'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/settings/story-models'
    | '/settings/web-search'
    | '/threads/$threadId'
    | '/settings/providers/$providerName'
    | '/settings/providers'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/events'
    | '/evolve'
    | '/logs'
    | '/manuscript'
    | '/submission'
    | '/world'
    | '/project/$projectId'
    | '/settings/assistant'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/https-proxy'
    | '/settings/interface'
    | '/settings/mcp-servers'
    | '/settings/privacy'
    | '/settings/shortcuts'
    | '/settings/story-models'
    | '/settings/web-search'
    | '/threads/$threadId'
    | '/settings/providers/$providerName'
    | '/settings/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRoute
  EventsRoute: typeof EventsRoute
  EvolveRoute: typeof EvolveRoute
  LogsRoute: typeof LogsRoute
  ManuscriptRoute: typeof ManuscriptRoute
  SubmissionRoute: typeof SubmissionRoute
  WorldRoute: typeof WorldRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  SettingsAssistantRoute: typeof SettingsAssistantRoute
  SettingsExtensionsRoute: typeof SettingsExtensionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsHttpsProxyRoute: typeof SettingsHttpsProxyRoute
  SettingsInterfaceRoute: typeof SettingsInterfaceRoute
  SettingsMcpServersRoute: typeof SettingsMcpServersRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  SettingsStoryModelsRoute: typeof SettingsStoryModelsRoute
  SettingsWebSearchRoute: typeof SettingsWebSearchRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  SettingsProvidersProviderNameRoute: typeof SettingsProvidersProviderNameRoute
  SettingsProvidersIndexRoute: typeof SettingsProvidersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission': {
      id: '/submission'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof SubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuscript': {
      id: '/manuscript'
      path: '/manuscript'
      fullPath: '/manuscript'
      preLoaderRoute: typeof ManuscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolve': {
      id: '/evolve'
      path: '/evolve'
      fullPath: '/evolve'
      preLoaderRoute: typeof EvolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/web-search': {
      id: '/settings/web-search'
      path: '/settings/web-search'
      fullPath: '/settings/web-search'
      preLoaderRoute: typeof SettingsWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/story-models': {
      id: '/settings/story-models'
      path: '/settings/story-models'
      fullPath: '/settings/story-models'
      preLoaderRoute: typeof SettingsStoryModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/shortcuts': {
      id: '/settings/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mcp-servers': {
      id: '/settings/mcp-servers'
      path: '/settings/mcp-servers'
      fullPath: '/settings/mcp-servers'
      preLoaderRoute: typeof SettingsMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/interface': {
      id: '/settings/interface'
      path: '/settings/interface'
      fullPath: '/settings/interface'
      preLoaderRoute: typeof SettingsInterfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/https-proxy': {
      id: '/settings/https-proxy'
      path: '/settings/https-proxy'
      fullPath: '/settings/https-proxy'
      preLoaderRoute: typeof SettingsHttpsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/extensions': {
      id: '/settings/extensions'
      path: '/settings/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof SettingsExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/assistant': {
      id: '/settings/assistant'
      path: '/settings/assistant'
      fullPath: '/settings/assistant'
      preLoaderRoute: typeof SettingsAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers/': {
      id: '/settings/providers/'
      path: '/settings/providers'
      fullPath: '/settings/providers/'
      preLoaderRoute: typeof SettingsProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers/$providerName': {
      id: '/settings/providers/$providerName'
      path: '/settings/providers/$providerName'
      fullPath: '/settings/providers/$providerName'
      preLoaderRoute: typeof SettingsProvidersProviderNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRoute,
  EventsRoute: EventsRoute,
  EvolveRoute: EvolveRoute,
  LogsRoute: LogsRoute,
  ManuscriptRoute: ManuscriptRoute,
  SubmissionRoute: SubmissionRoute,
  WorldRoute: WorldRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  SettingsAssistantRoute: SettingsAssistantRoute,
  SettingsExtensionsRoute: SettingsExtensionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsHttpsProxyRoute: SettingsHttpsProxyRoute,
  SettingsInterfaceRoute: SettingsInterfaceRoute,
  SettingsMcpServersRoute: SettingsMcpServersRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  SettingsStoryModelsRoute: SettingsStoryModelsRoute,
  SettingsWebSearchRoute: SettingsWebSearchRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  SettingsProvidersProviderNameRoute: SettingsProvidersProviderNameRoute,
  SettingsProvidersIndexRoute: SettingsProvidersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
