#!/bin/bash
APPIMAGETOOL="./.cache/build-tools/appimagetool"
RELEASE_CHANNEL=${RELEASE_CHANNEL:-"stable"}

mkdir -p ./.cache/build-tools
wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O "${APPIMAGETOOL}" || { echo "Failed to download appimagetool."; exit 1; }
chmod +x "${APPIMAGETOOL}"

if [ "${RELEASE_CHANNEL}" != "stable" ]; then
    APP_NAME="Story Engine ${RELEASE_CHANNEL}"
else
    APP_NAME="Story Engine"
fi

APP_DIR="./src-tauri/target/release/bundle/appimage/${APP_NAME}.AppDir"
LIB_DIR="${APP_DIR}/usr/lib/${APP_NAME}/binaries"

# bundle additional resources in the AppDir without pulling in their dependencies
cp ./src-tauri/resources/bin/bun "$APP_DIR/usr/bin/bun"
mkdir -p "$LIB_DIR/engines"

# remove appimage generated by tauri build
APPIMAGE_DIR="./src-tauri/target/release/bundle/appimage"
APP_IMAGE=""
while IFS= read -r -d '' CANDIDATE; do
    if [ -n "${APP_IMAGE}" ]; then
        echo "Expected exactly one generated AppImage in ${APPIMAGE_DIR}." >&2
        exit 1
    fi
    APP_IMAGE="${CANDIDATE}"
done < <(find "${APPIMAGE_DIR}" -maxdepth 1 -type f -name '*.AppImage' -print0)

if [ -z "${APP_IMAGE}" ]; then
    echo "No generated AppImage found in ${APPIMAGE_DIR}." >&2
    exit 1
fi

echo "${APP_IMAGE}"
rm -f -- "${APP_IMAGE}"

# repackage appimage with additional resources
"${APPIMAGETOOL}" "$APP_DIR" "$APP_IMAGE"
